### ISSUE TITLE
Cannot generate app config

### ISSUE THREAD

**Issue by jubayerarefin** [cuonggt/larasearch#1]
I have just installed the package. However I can't publish the config. When I run the `php artisan vendor:publish` command it gives the this error:
`PHP Parse error:  syntax error, unexpected '::' (T_PAAMAYIM_NEKUDOTAYIM) in .../vendor/gtk/larasearch/src/Console/ClearCommand.php on line 34`

It might be related to your latest commit.

Thanks for making this package.

**Comment by cuonggt** [comment]
Thank you for your comment!

There're some bugs and I've already fixed them. Please update to the latest release (v1.1.3). Sorry for the inconvenience!

**Comment by jubayerarefin** [comment]
Thanks for your reply. Will checkout the latest version.
